name: lightgun_wiimote
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: 5.0.0-nullsafety.5 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true